/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppInstallRouteImport } from './routes/app-install'
import { Route as ChannelPreferenceRouteImport } from './routes/channel-preference'
import { Route as EmailRouteImport } from './routes/email'
import { Route as GameRouteImport } from './routes/game'
import { Route as GameIntroRouteImport } from './routes/game-intro'
import { Route as PhoneRouteImport } from './routes/phone'
import { Route as PhoneHomeRouteImport } from './routes/phone-home'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as SmsRouteImport } from './routes/sms'
import { Route as WhatsappRouteImport } from './routes/whatsapp'
import { Route as WinRouteImport } from './routes/win'
import { Route as AppProgressRouteImport } from './routes/app.progress'
import { Route as AppRoadmapRouteImport } from './routes/app.roadmap'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppInstallRoute = AppInstallRouteImport.update({
  id: '/app-install',
  path: '/app-install',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelPreferenceRoute = ChannelPreferenceRouteImport.update({
  id: '/channel-preference',
  path: '/channel-preference',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailRoute = EmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => rootRouteImport,
} as any)
const GameRoute = GameRouteImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => rootRouteImport,
} as any)
const GameIntroRoute = GameIntroRouteImport.update({
  id: '/game-intro',
  path: '/game-intro',
  getParentRoute: () => rootRouteImport,
} as any)
const PhoneRoute = PhoneRouteImport.update({
  id: '/phone',
  path: '/phone',
  getParentRoute: () => rootRouteImport,
} as any)
const PhoneHomeRoute = PhoneHomeRouteImport.update({
  id: '/phone-home',
  path: '/phone-home',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const SmsRoute = SmsRouteImport.update({
  id: '/sms',
  path: '/sms',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatsappRoute = WhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const WinRoute = WinRouteImport.update({
  id: '/win',
  path: '/win',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProgressRoute = AppProgressRouteImport.update({
  id: '/app/progress',
  path: '/app/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoadmapRoute = AppRoadmapRouteImport.update({
  id: '/app/roadmap',
  path: '/app/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app-install': typeof AppInstallRoute
  '/channel-preference': typeof ChannelPreferenceRoute
  '/email': typeof EmailRoute
  '/game': typeof GameRoute
  '/game-intro': typeof GameIntroRoute
  '/phone': typeof PhoneRoute
  '/phone-home': typeof PhoneHomeRoute
  '/schedule': typeof ScheduleRoute
  '/sms': typeof SmsRoute
  '/whatsapp': typeof WhatsappRoute
  '/win': typeof WinRoute
  '/app/progress': typeof AppProgressRoute
  '/app/roadmap': typeof AppRoadmapRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app-install': typeof AppInstallRoute
  '/channel-preference': typeof ChannelPreferenceRoute
  '/email': typeof EmailRoute
  '/game': typeof GameRoute
  '/game-intro': typeof GameIntroRoute
  '/phone': typeof PhoneRoute
  '/phone-home': typeof PhoneHomeRoute
  '/schedule': typeof ScheduleRoute
  '/sms': typeof SmsRoute
  '/whatsapp': typeof WhatsappRoute
  '/win': typeof WinRoute
  '/app/progress': typeof AppProgressRoute
  '/app/roadmap': typeof AppRoadmapRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app-install': typeof AppInstallRoute
  '/channel-preference': typeof ChannelPreferenceRoute
  '/email': typeof EmailRoute
  '/game': typeof GameRoute
  '/game-intro': typeof GameIntroRoute
  '/phone': typeof PhoneRoute
  '/phone-home': typeof PhoneHomeRoute
  '/schedule': typeof ScheduleRoute
  '/sms': typeof SmsRoute
  '/whatsapp': typeof WhatsappRoute
  '/win': typeof WinRoute
  '/app/progress': typeof AppProgressRoute
  '/app/roadmap': typeof AppRoadmapRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app-install'
    | '/channel-preference'
    | '/email'
    | '/game'
    | '/game-intro'
    | '/phone'
    | '/phone-home'
    | '/schedule'
    | '/sms'
    | '/whatsapp'
    | '/win'
    | '/app/progress'
    | '/app/roadmap'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app-install'
    | '/channel-preference'
    | '/email'
    | '/game'
    | '/game-intro'
    | '/phone'
    | '/phone-home'
    | '/schedule'
    | '/sms'
    | '/whatsapp'
    | '/win'
    | '/app/progress'
    | '/app/roadmap'
  id:
    | '__root__'
    | '/'
    | '/app-install'
    | '/channel-preference'
    | '/email'
    | '/game'
    | '/game-intro'
    | '/phone'
    | '/phone-home'
    | '/schedule'
    | '/sms'
    | '/whatsapp'
    | '/win'
    | '/app/progress'
    | '/app/roadmap'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppInstallRoute: typeof AppInstallRoute
  ChannelPreferenceRoute: typeof ChannelPreferenceRoute
  EmailRoute: typeof EmailRoute
  GameRoute: typeof GameRoute
  GameIntroRoute: typeof GameIntroRoute
  PhoneRoute: typeof PhoneRoute
  PhoneHomeRoute: typeof PhoneHomeRoute
  ScheduleRoute: typeof ScheduleRoute
  SmsRoute: typeof SmsRoute
  WhatsappRoute: typeof WhatsappRoute
  WinRoute: typeof WinRoute
  AppProgressRoute: typeof AppProgressRoute
  AppRoadmapRoute: typeof AppRoadmapRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app-install': {
      id: '/app-install'
      path: '/app-install'
      fullPath: '/app-install'
      preLoaderRoute: typeof AppInstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channel-preference': {
      id: '/channel-preference'
      path: '/channel-preference'
      fullPath: '/channel-preference'
      preLoaderRoute: typeof ChannelPreferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email': {
      id: '/email'
      path: '/email'
      fullPath: '/email'
      preLoaderRoute: typeof EmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game': {
      id: '/game'
      path: '/game'
      fullPath: '/game'
      preLoaderRoute: typeof GameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game-intro': {
      id: '/game-intro'
      path: '/game-intro'
      fullPath: '/game-intro'
      preLoaderRoute: typeof GameIntroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phone': {
      id: '/phone'
      path: '/phone'
      fullPath: '/phone'
      preLoaderRoute: typeof PhoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phone-home': {
      id: '/phone-home'
      path: '/phone-home'
      fullPath: '/phone-home'
      preLoaderRoute: typeof PhoneHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sms': {
      id: '/sms'
      path: '/sms'
      fullPath: '/sms'
      preLoaderRoute: typeof SmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whatsapp': {
      id: '/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof WhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/win': {
      id: '/win'
      path: '/win'
      fullPath: '/win'
      preLoaderRoute: typeof WinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/progress': {
      id: '/app/progress'
      path: '/app/progress'
      fullPath: '/app/progress'
      preLoaderRoute: typeof AppProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/roadmap': {
      id: '/app/roadmap'
      path: '/app/roadmap'
      fullPath: '/app/roadmap'
      preLoaderRoute: typeof AppRoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppInstallRoute: AppInstallRoute,
  ChannelPreferenceRoute: ChannelPreferenceRoute,
  EmailRoute: EmailRoute,
  GameRoute: GameRoute,
  GameIntroRoute: GameIntroRoute,
  PhoneRoute: PhoneRoute,
  PhoneHomeRoute: PhoneHomeRoute,
  ScheduleRoute: ScheduleRoute,
  SmsRoute: SmsRoute,
  WhatsappRoute: WhatsappRoute,
  WinRoute: WinRoute,
  AppProgressRoute: AppProgressRoute,
  AppRoadmapRoute: AppRoadmapRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
